### ISSUE TITLE
Parameters.xml and JSON files

### ISSUE THREAD

**Issue by vitaliipanchenko** [microsoft/azure-pipelines-extensions#512]
How sould I write parameters.xml if i wan`t to transform JSON file during deploy (WinRM IIS web app deployment task)?

**Comment by Ajay-MS** [comment]
@vitaliipanchenko 

This task doesn't support directly the file transformation. You can use  `File Transformation` task. 

Using `File Transformation` task, in order to update JSON file you don't need to change in Parameter.xml. You can directly update the JSON file using `JSON substitution`  feature of the task.
