### ISSUE TITLE
How to create web app under the web site

### ISSUE THREAD

**Issue by jagdaleganesh** [microsoft/azure-pipelines-extensions#557]
is it possible to use this task to create web app or virtual directory using this taks. I have tried by giving [WebSiteName]\[WebAppname] but it throws an error .
Please help

**Comment by Ajay-MS** [comment]
@jagdaleganesh 

We apologise for the delay in the response. 

I tried creating website as well as virtual directory and able to create successfully. Can you please share debug logs in order to analyse why it's failing in your case. 

Debug logs can be enabled by adding a release variable `system.deug` with value `true`

**Comment by Ajay-MS** [comment]
Closing as no repro. Feel free to reopen with debug logs.
