### ISSUE TITLE
ServiceNow enable open change on agentless task

### ISSUE THREAD

**Issue by Ghkuijer** [microsoft/azure-pipelines-extensions#715]
In our organization we would like to change all of our pipelines to yaml pipelines since that would enable better control on the changes on our pipelines.

The only limitation we currently have is the ServiceNow integration to create changes. Gates are not available in yaml pipelines but the open change task can only be used as a gate.

Is there a possibility it can be enabled as an agentless task so we can run it in a yaml pipeline?

**Comment by shashban** [comment]
@Ghkuijer You are right. The support for checks (gates) for yaml pipelines are evolving. We are taking an approach of segregating the roles as check definition for infrastructure (environment) owners and pipeline process for developers. Currently only approvals are available as a check. We will support ServiceNow change management as a check soon.
In the meantime, you can use our code to have a custom task to create a change request. It would not wait for the approval workflow to complete before allowing deployments to happen. Our task would always fail if used in a server job due to non-matching change status.

**Comment by Ghkuijer** [comment]
Thanks for the fast replies @shashban. Great to hear that the checks for Azure DevOps will be extended soon. Meanwhile we will try to use a custom task for opening the change. 
I'll close this issue.
