### ISSUE TITLE
Terraform Extension puts the AzureRM connection secret in plain text in the terminal

### ISSUE THREAD

**Issue by gabrielmccoll** [microsoft/azure-pipelines-extensions#872]
- task: TerraformTaskV1@0
        displayName: 'init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(TerraformWorkingDirectory)'
          backendServiceArm: '$(ServiceConnection)'
          backendAzureRmResourceGroupName: '$(ResourceGroup)'
          backendAzureRmStorageAccountName: '$(ResourceGroup)'
          backendAzureRmContainerName: 'tfstatedevops165'
          backendAzureRmKey: 'terraform.tfstate'

Snipped off some for security but it seems strange that many of th pieces are *** but not the secret?

![image](https://user-images.githubusercontent.com/25871665/96610958-17781d00-12f4-11eb-8de7-ff29a464c08c.png)

**Comment by Roshan-Kumar-Microsoft** [comment]
@gabrielmccoll We are always mocking Secret . I tested with latest terraform version and we are mocking it .
Can you confirm are you using microsoft terra extension ? because on marketplace there are multiple terraform extension but we are releasing through Microsoft publisher 
![image](https://user-images.githubusercontent.com/57892372/97419600-444db500-1930-11eb-987e-55e13b20da8f.png)

I tested and it is working fine 
![image](https://user-images.githubusercontent.com/57892372/97419668-54fe2b00-1930-11eb-8d5f-89dc2820ac21.png)

![image](https://user-images.githubusercontent.com/57892372/97419697-60e9ed00-1930-11eb-804a-c9051e3ee5ec.png)

Can you please verify it ?  Can you also attach debug log and send it to RM_Customer_Queries@microsoft.com

**Comment by gabrielmccoll** [comment]
Hi there. I only had one at the time which was the devlabs one so am pretty sure. I'm not back at work until Monday to check unfortunately. I switched to a different extension after I reported this because of this issue

**Comment by AmrutaKawade** [comment]
@gabrielmccoll can you verify once?

**Comment by AmrutaKawade** [comment]
We verified this and its not getting logged. Feel free to reopen if you see this issue again with detail logs. Closing this issue
